name: Docker Build and Push

# Trigger the pipeline on push and pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Define the job that runs the build and deploy process
  build_and_push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu version
    steps:
    
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Store your Docker Hub username in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Store your Docker Hub password in GitHub Secrets

    # Build and push the backend Docker image
    - name: Build and push backend Docker image
      run: |
        docker build -t chihebben008/backend:latest -f ./backend/Dockerfile ./backend
        docker push chihebben008/backend:latest

    # Build and push the frontend Docker image
    - name: Build and push frontend Docker image
      run: |
        docker build -t chihebben008/frontend:latest -f ./frontend/Dockerfile ./frontend
        docker push chihebben008/frontend:latest

